const emojis = [
	{ img: '🍇', description: 'grapes', code: '&#x1F347' },
	// { img: '🍈', description: 'melon', code: '&#x1F348' },
	{ img: '🍉', description: 'water melon', code: '&#x1F349' },
	{ img: '🍊', description: 'tangerine', code: '&#x1F34A' },
	{ img: '🍋', description: 'lime', code: '&#x1F34B' },
	{ img: '🍌', description: 'banana', code: '&#x1F34C' },
	{ img: '🍍', description: 'pineapple', code: '&#x1F34D' },
	{ img: '🥭', description: 'mango', code: '&#x1F96D' },
	{ img: '🍎', description: 'red apple', code: '&#x1F34E' },
	// { img: '🍏', description: 'green apple', code: '&#x1F34F' },
	// { img: '🍐', description: 'pear', code: '&#x1F350' },
	{ img: '🍑', description: 'peach', code: '&#x1F351' },
	// { img: '🍒', description: 'cherries', code: '&#x1F352' },
	{ img: '🍓', description: 'strawberries', code: '&#x1F353' },
	{ img: '🫐', description: 'blueberries', code: '&#x1FAD0' },
	// { img: '🥝', description: 'kiwi fruit', code: '&#x1F95D' },
	{ img: '🍅', description: 'tomato', code: '&#x1F345' },
	{ img: '🫒', description: 'olive', code: '&#x1FAD2' },
	// { img: '🥥', description: 'coconut', code: '&#x1F965' },
	{ img: '🥑', description: 'avocado', code: '&#x1F951' },
	// { img: '🍆', description: 'eggplant', code: '&#x1F346' },
	{ img: '🥔', description: 'potato', code: '&#x1F954' },
	{ img: '🥕', description: 'carrot', code: '&#x1F955' },
	{ img: '🌽', description: 'corn', code: '&#x1F33D' },
	{ img: '🌶', description: 'pepper', code: '&#x1F336' },
	{ img: '🫑', description: 'bell pepper', code: '&#x1FAD1' },
	{ img: '🥒', description: 'cucumber', code: '&#x1F952' },
	{ img: '🥬', description: 'leafy green', code: '&#x1F96C' },
	{ img: '🥦', description: 'broccoli', code: '&#x1F966' },
	{ img: '🧄', description: 'garlic', code: '&#x1F9C4' },
	{ img: '🧅', description: 'onion', code: '&#x1F9C5' },
	{ img: '🍄', description: 'mushroom', code: '&#x1F344' },
	// { img: '🥜', description: 'peanuts', code: '&#x1F95C' },
	{ img: '🫑', description: 'beans', code: '&#x1FAD8' },
	// { img: '🌰', description: 'chestnut', code: '&#x1F330' },
	{ img: '🍞', description: 'bread', code: '&#x1F35E' },
	// { img: '🥐', description: 'croissant', code: '&#x1F950' },
	{ img: '🥖', description: 'baguette bread', code: '&#x1F956' },
	{ img: '🫓', description: 'flat bread', code: '&#x1FAD3' },
	// { img: '🥨', description: 'pretzel', code: '&#x1F968' },
	{ img: '🥯', description: 'bagel', code: '&#x1F96F' },
	// { img: '🥞', description: 'pancake', code: '&#x1F95E' },
	{ img: '🧇', description: 'waffle', code: '&#x1F9C7' },
	{ img: '🧀', description: 'cheese wedge', code: '&#x1F9C0' },
	{ img: '🍖', description: 'meat with bone', code: '&#x1F356' },
	{ img: '🍗', description: 'poultry leg', code: '&#x1F357' },
	{ img: '🥩', description: 'cut of meat', code: '&#x1F969' },
	{ img: '🥓', description: 'bacon', code: '&#x1F953' },
	// { img: '🍔', description: 'hamburger', code: '&#x1F354' },
	// { img: '🍟', description: 'french fries', code: '&#x1F35F' },
	{ img: '🍕', description: 'pizza', code: '&#x1F355' },
	// { img: '🌭', description: 'hot dog', code: '&#x1F32D' },
	// { img: '🥪', description: 'sandwich', code: '&#x1F96A' },
	// { img: '🌮', description: 'taco', code: '&#x1F32E' },
	// { img: '🌯', description: 'burrito', code: '&#x1F32F' },
	// { img: '🫔', description: 'tamale', code: '&#x1FAD4' },
	// { img: '🥙', description: 'stuffed flatbread', code: '&#x1F959' },
	// { img: '🧆', description: 'falafel', code: '&#x1F9C6' },
	{ img: '🥚', description: 'egg', code: '&#x1F95A' },
	// { img: '🍳', description: 'cooking', code: '&#x1F373' },
	// { img: '🥘', description: 'shallow pan of food', code: '&#x1F958' },
	{ img: '🍲', description: 'pot of food', code: '&#x1F372' },
	// { img: '🥣', description: 'bowl with food', code: '&#x1F963' },
	{ img: '🥗', description: 'green salad', code: '&#x1F957' },
	{ img: '🍿', description: 'popcorn', code: '&#x1F37F' },
	{ img: '🧈', description: 'butter', code: '&#x1F9C8' },
	{ img: '🧂', description: 'salt', code: '&#x1F9C2' },
	// { img: '🥫', description: 'canned food', code: '&#x1F96B' },
	// { img: '🍱', description: 'bento box', code: '&#x1F371' },
	{ img: '🍚', description: 'cooked rice', code: '&#x1F35A' },
	// { img: '🍠', description: 'roasted sweet potato', code: '&#x1F360' },
	{ img: '🦀', description: 'crab', code: '&#x1F980' },
	{ img: '🦞', description: 'lobster', code: '&#x1F99E' },
	{ img: '🦐', description: 'shrimp', code: '&#x1F990' },
	// { img: '🦪', description: 'oyster', code: '&#x1F9AA' },
	{ img: '🍨', description: 'ice cream', code: '&#x1F368' },
	{ img: '🍦', description: 'soft ice cream', code: '&#x1F366' },
	// { img: '🍩', description: 'doughnut', code: '&#x1F369' },
	{ img: '🍪', description: 'cookie', code: '&#x1F36A' },
	// { img: '🎂', description: 'birthday cake', code: '&#x1F382' },
	// { img: '🍰', description: 'short cake', code: '&#x1F370' },
	// { img: '🧁', description: 'cup cake', code: '&#x1F9C1' },
	{ img: '🥧', description: 'pie', code: '&#x1F967' },
	{ img: '🍫', description: 'chocoloate', code: '&#x1F36B' },
	{ img: '🍯', description: 'honey pot', code: '&#x1F36F' },
	{ img: '🥛', description: 'glass of milk', code: '&#x1F95B' },
	// { img: '☕', description: 'hot beverage', code: '&#x2615' },
	{ img: '🍵', description: 'teacup without handle', code: '&#x1F375' },
	// { img: '🍾', description: 'bottle with poppin cork', code: '&#x1F37E' },
	{ img: '🍷', description: 'wine glass', code: '&#x1F377' },
	// { img: '🍸', description: 'cocktail glass', code: '&#x1F378' },
	// { img: '🍹', description: 'tropical drink', code: '&#x1F379' },
	{ img: '🍺', description: 'beer mug', code: '&#x1F37A' }
	// { img: '🥃', description: 'tumbler glass', code: '&#x1F943' }
];

export default emojis;
